### ISSUE TITLE
Cross-origin frame errors disabling button

### ISSUE THREAD

**Issue by slimjim777** [sirkitree/angular-directive.g-signin#24]
I've just tried loading the example on your site and am getting cross-origin frame errors on page load. These are stopping the sign-in button from being active. This is happening in Chromium/Chrome on Ubuntu 14.04. The button works in Firefox.
```
Chromium	34.0.1847.116 (Developer Build 260972) Ubuntu 14.04 aura
OS	Linux 
Blink	537.36 (@170605)
JavaScript	V8 3.24.35.22
```
```
Error in event handler for (unknown): Blocked a frame with origin "https://apis.google.com" from accessing a cross-origin frame.
Stack trace: Error: Blocked a frame with origin "https://apis.google.com" from accessing a cross-origin frame.
    at Error (native)
    at setupffoverrides (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:151:86)
    at checkgenpwfillforms (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:152:33)
    at receiveBG (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:130:210)
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at EventImpl.dispatchToListener (extensions::event_bindings:395:22)
    at Function.target.(anonymous function) (extensions::SafeBuiltins:19:14)
    at publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:69:26)
    at EventImpl.dispatch_ (extensions::event_bindings:378:35)
    at EventImpl.dispatch (extensions::event_bindings:401:17) extensions::event_bindings:383
EventImpl.dispatch_ extensions::event_bindings:383
EventImpl.dispatch extensions::event_bindings:401
publicClass.(anonymous function) extensions::utils:69
dispatchOnMessage
```

This is only one of the errors - there are similar ones for the accounts.google.com URL.

**Comment by bobleujr** [comment]
A couple of things can solve this issue.

The first one is trying to clean your cache.

Second, go to your console.developers.google.com, under Consent Screen and try checking if your app name and email are set up.
